"""add Pattern key

Revision ID: 4ccab8b673b7
Revises: 
Create Date: 2022-01-18 16:53:21.344331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccab8b673b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patterns', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('patterns', sa.Column('special_handle', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patterns', 'special_handle')
    op.drop_column('patterns', 'extra')
    # ### end Alembic commands ###
